# Generated by Django 4.2.5 on 2023-10-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('price', models.IntegerField(null=True)),
                ('size', models.CharField(choices=[('large', 'large'), ('medium', 'medium'), ('mini', 'mini')], default='medium', max_length=6)),
                ('color', models.CharField(choices=[('white', 'white'), ('balck', 'balck')], default='balck', max_length=5))
            ],
        ),
    ]
