# Generated by Django 4.2.5 on 2023-10-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='color',
            field=models.CharField(choices=[('white', 'white'), ('black', 'black')], default='hot', max_length=5),
        ),
        migrations.AlterField(
            model_name='type',
            name='size',
            field=models.CharField(choices=[('large', 'large'), ('medium', 'medium'), ('mini', 'mini')], default='medium', max_length=6),
        ),
    ]
