# Generated by Django 4.2.5 on 2023-10-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0002_type_color_alter_type_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='sajin',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
