# Generated by Django 4.2.5 on 2023-10-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0003_type_sajin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='color',
            field=models.CharField(choices=[('white', 'white'), ('black', 'balck')], default='black', max_length=5),
        ),
    ]
